{"sections":[],"metadata":{"role":"symbol","externalID":"c:@E@SMIChallengeReason@SMIChallengeReasonMalformed","title":"SMIChallengeReasonMalformed","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}],"fragments":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}],"roleHeading":"Enumeration Case","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/smichallengereason\/smichallengereasonmalformed"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SMIChallengeReasonMalformed","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason\/SMIChallengeReasonMalformed","interfaceLanguage":"occ"},"kind":"symbol","abstract":[{"text":"The passed in token was malformed.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIChallengeReason":{"type":"topic","fragments":[{"kind":"identifier","text":"SMIChallengeReason"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason","url":"\/documentation\/smiclientcore\/smichallengereason","abstract":[{"type":"text","text":"The reason for a credential challenge. Possible values:"}],"kind":"symbol","role":"symbol","title":"SMIChallengeReason"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIChallengeReason/SMIChallengeReasonMalformed":{"type":"topic","abstract":[{"type":"text","text":"The passed in token was malformed."}],"fragments":[{"text":"SMIChallengeReasonMalformed","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/smichallengereason\/smichallengereasonmalformed","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason\/SMIChallengeReasonMalformed","title":"SMIChallengeReasonMalformed","role":"symbol","kind":"symbol"}}}