{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason\/SMIChallengeReasonMalformed","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"The passed in token was malformed.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"SMIChallengeReasonMalformed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/smichallengereason\/smichallengereasonmalformed"]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMIChallengeReasonMalformed","kind":"identifier"}],"title":"SMIChallengeReasonMalformed","externalID":"c:@E@SMIChallengeReason@SMIChallengeReasonMalformed","symbolKind":"case","roleHeading":"Enumeration Case","role":"symbol","fragments":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"abstract":[],"kind":"symbol","type":"topic","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","url":"\/documentation\/smiclientcore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIChallengeReason":{"title":"SMIChallengeReason","url":"\/documentation\/smiclientcore\/smichallengereason","fragments":[{"kind":"identifier","text":"SMIChallengeReason"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The reason for a credential challenge. Possible values:"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIChallengeReason/SMIChallengeReasonMalformed":{"kind":"symbol","abstract":[{"text":"The passed in token was malformed.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"SMIChallengeReasonMalformed","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/smichallengereason\/smichallengereasonmalformed","title":"SMIChallengeReasonMalformed","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason\/SMIChallengeReasonMalformed"}}}